---
- name: Install needed packages
  yum:
    name:
      - podman
      - openssl-devel
      - make
    state: present

- name: install ISO generator scripts
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-iso-generator"

- name: install racadm
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-racadm"
  when: need_racadm|bool == True

- name: install aicli
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-aicli"

- name: install assisted installer
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-assisted-installer"
  vars:
    onprem_vars:
      - - "SUPPORT_L2=false"
        - "SERVICE_BASE_URL={{ ai_url }}"
        - "HW_VALIDATOR_MIN_DISK_SIZE_GIB=50"
        - "OPENSHIFT_VERSIONS={\"4.6\":{\"display_name\":\"4.6.12\",\"release_image\":\"quay.io/openshift-release-dev/ocp-release:4.6.12-x86_64\",\"rhcos_image\":\"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso\",\"rhcos_version\":\"46.82.202012051820-0\",\"support_level\":\"production\"},\"4.7\":{\"display_name\":\"4.7-pre-release\",\"release_image\":\"quay.io/openshift-release-dev/ocp-release:4.7.0-fc.4-x86_64\",\"rhcos_image\":\"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.7.0-fc.4/rhcos-4.7.0-fc.4-x86_64-live.x86_64.iso\",\"rhcos_version\":\"47.83.202101171239-0\",\"support_level\":\"beta\"},\"4.8\":{\"display_name\":\"4.7-single-node-alpha\",\"release_image\":\"registry.svc.ci.openshift.org/sno-dev/openshift-bip:0.2.0\",\"rhcos_image\":\"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.7.0-fc.4/rhcos-4.7.0-fc.4-x86_64-live.x86_64.iso\",\"rhcos_version\":\"47.83.202101171239-0\",\"support_level\":\"beta\"}}"
        - "OPENSHIFT_INSTALL_RELEASE_IMAGE={{ sno_image }}"
        - "PUBLIC_CONTAINER_REGISTRIES=quay.io,registry.svc.ci.openshift.org"


